name: OpenWrt Plugin CI Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      SDK_NAME: openwrt-sdk-19.07.2-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64
      SDK_URL: https://downloads.openwrt.org/releases/19.07.2/targets/ramips/mt7621/openwrt-sdk-19.07.2-ramips-mt7621_gcc-7.5.0_musl.Linux-x86_64.tar.xz
    steps:
    - name: Checkout - clone repository
      uses: actions/checkout@v1
    - name: Install - system build dependencies
      run: sudo apt-get install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: Download - sdk archive download
      run: |
        wget $SDK_URL
        xz -d $SDK_NAME.tar.xz
        tar xf $SDK_NAME.tar
    - name: Clone - openwrt plugin source
      run: |
        cd $SDK_NAME
        git clone https://github.com/flytosky-f/openwrt-vlmcsd.git package/openwrt-vlmcsd
        git clone https://github.com/pymumu/openwrt-smartdns.git package/openwrt-smartdns
        git clone https://github.com/pymumu/luci-app-smartdns.git package/luci-app-smartdns
    - name: Make - make default config
      run: |
        cd $SDK_NAME
        make defconfig
    - name: Build - make openwrt plugin
      run: |
        cd $SDK_NAME
        make package/openwrt-vlmcsd/compile V=99
    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-plugin
        path: ${{ env.SDK_NAME }}/bin/packages/mipsel_24kc/
